export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const UPADATE_PURCHASABLE = "UPADATE_PURCHASABLE";

export const RESET_INGREDIENTS = "RESET_INGREDIENTS";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const LOAD_FAILED = "LOAD_FAILED";